### ISSUE TITLE
PIP fails.

### ISSUE THREAD

**Issue by Hammersamatom** [baxter-cs/AndOre#200]
(master-env)andore@AndOre-DevPi:~/AndOre/client $ pip install -r requirements.txt
Downloading/unpacking click==6.6 (from -r requirements.txt (line 1))
  Downloading click-6.6.tar.gz (283kB): 283kB downloaded
  Running setup.py (path:/tmp/pip-build-a3brlnjd/click/setup.py) egg_info for package click

    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
    warning: no previously-included files matching '*.pyo' found under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'examples'
    warning: no previously-included files matching '*.pyo' found under directory 'examples'
    no previously-included directories found matching 'docs/_build'
Downloading/unpacking Flask==0.11.1 (from -r requirements.txt (line 2))
  Downloading Flask-0.11.1-py2.py3-none-any.whl (80kB): 80kB downloaded
Downloading/unpacking itsdangerous==0.24 (from -r requirements.txt (line 3))
  Downloading itsdangerous-0.24.tar.gz (46kB): 46kB downloaded
  Running setup.py (path:/tmp/pip-build-a3brlnjd/itsdangerous/setup.py) egg_info for package itsdangerous

    warning: no previously-included files matching '*' found under directory 'docs/_build'
Downloading/unpacking Jinja2==2.8 (from -r requirements.txt (line 4))
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB): 263kB downloaded
Downloading/unpacking MarkupSafe==0.23 (from -r requirements.txt (line 5))
  Downloading MarkupSafe-0.23.tar.gz
  Running setup.py (path:/tmp/pip-build-a3brlnjd/MarkupSafe/setup.py) egg_info for package MarkupSafe

Downloading/unpacking pkg-resources==0.0.0 (from -r requirements.txt (line 6))
  Could not find any downloads that satisfy the requirement pkg-resources==0.0.0 (from -r requirements.txt (line 6))
Cleaning up...
No distributions at all found for pkg-resources==0.0.0 (from -r requirements.txt (line 6))
Storing debug log for failure in /home/andore/.pip/pip.log
(master-env)andore@AndOre-DevPi:~/AndOre/client $ nano requirements.txt
(master-env)andore@AndOre-DevPi:~/AndOre/client $ pip install -r requirements.txt
Downloading/unpacking click==6.6 (from -r requirements.txt (line 1))
  Downloading click-6.6.tar.gz (283kB): 283kB downloaded
  Running setup.py (path:/tmp/pip-build-yonpcs2h/click/setup.py) egg_info for package click

    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
    warning: no previously-included files matching '*.pyo' found under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'examples'
    warning: no previously-included files matching '*.pyo' found under directory 'examples'
    no previously-included directories found matching 'docs/_build'
Downloading/unpacking Flask==0.11.1 (from -r requirements.txt (line 2))
  Downloading Flask-0.11.1-py2.py3-none-any.whl (80kB): 80kB downloaded
Downloading/unpacking itsdangerous==0.24 (from -r requirements.txt (line 3))
  Downloading itsdangerous-0.24.tar.gz (46kB): 46kB downloaded
  Running setup.py (path:/tmp/pip-build-yonpcs2h/itsdangerous/setup.py) egg_info for package itsdangerous

    warning: no previously-included files matching '*' found under directory 'docs/_build'
Downloading/unpacking Jinja2==2.8 (from -r requirements.txt (line 4))
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB): 263kB downloaded
Downloading/unpacking MarkupSafe==0.23 (from -r requirements.txt (line 5))
  Downloading MarkupSafe-0.23.tar.gz
  Running setup.py (path:/tmp/pip-build-yonpcs2h/MarkupSafe/setup.py) egg_info for package MarkupSafe

Downloading/unpacking Werkzeug==0.11.10 (from -r requirements.txt (line 6))
  Downloading Werkzeug-0.11.10-py2.py3-none-any.whl (306kB): 306kB downloaded
Installing collected packages: click, Flask, itsdangerous, Jinja2, MarkupSafe, Werkzeug
  Running setup.py install for click
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-yonpcs2h/click/setup.py", line 26, in <module>
        'Programming Language :: Python :: 3',
      File "/usr/local/lib/python3.5/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.5/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/andore/master-env/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.5/distutils/command/install.py", line 551, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.5/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.5/distutils/dist.py", line 973, in run_command
        cmd_obj.ensure_finalized()
      File "/usr/local/lib/python3.5/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/home/andore/master-env/lib/python3.5/site-packages/setuptools/command/install_lib.py", line 16, in finalize_options
        self.set_undefined_options('install',('install_layout','install_layout'))
      File "/usr/local/lib/python3.5/distutils/cmd.py", line 290, in set_undefined_options
        setattr(self, dst_option, getattr(src_cmd_obj, src_option))
      File "/usr/local/lib/python3.5/distutils/cmd.py", line 103, in __getattr__
        raise AttributeError(attr)
    AttributeError: install_layout
    Complete output from command /home/andore/master-env/bin/python3.5 -c "import setuptools, tokenize;__file__='/tmp/pip-build-yonpcs2h/click/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-z_f40fma-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/andore/master-env/include/site/python3.5:
    running install

running build

running build_py

creating build

creating build/lib

creating build/lib/click

copying click/__init__.py -> build/lib/click

copying click/_termui_impl.py -> build/lib/click

copying click/utils.py -> build/lib/click

copying click/_unicodefun.py -> build/lib/click

copying click/parser.py -> build/lib/click

copying click/decorators.py -> build/lib/click

copying click/core.py -> build/lib/click

copying click/_winconsole.py -> build/lib/click

copying click/_bashcomplete.py -> build/lib/click

copying click/termui.py -> build/lib/click

copying click/testing.py -> build/lib/click

copying click/_textwrap.py -> build/lib/click

copying click/globals.py -> build/lib/click

copying click/_compat.py -> build/lib/click

copying click/types.py -> build/lib/click

copying click/exceptions.py -> build/lib/click

copying click/formatting.py -> build/lib/click

running install_lib

Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip-build-yonpcs2h/click/setup.py", line 26, in <module>

    'Programming Language :: Python :: 3',

  File "/usr/local/lib/python3.5/distutils/core.py", line 148, in setup

    dist.run_commands()

  File "/usr/local/lib/python3.5/distutils/dist.py", line 955, in run_commands

    self.run_command(cmd)

  File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command

    cmd_obj.run()

  File "/home/andore/master-env/lib/python3.5/site-packages/setuptools/command/install.py", line 61, in run

    return orig.install.run(self)

  File "/usr/local/lib/python3.5/distutils/command/install.py", line 551, in run

    self.run_command(cmd_name)

  File "/usr/local/lib/python3.5/distutils/cmd.py", line 313, in run_command

    self.distribution.run_command(command)

  File "/usr/local/lib/python3.5/distutils/dist.py", line 973, in run_command

    cmd_obj.ensure_finalized()

  File "/usr/local/lib/python3.5/distutils/cmd.py", line 107, in ensure_finalized

    self.finalize_options()

  File "/home/andore/master-env/lib/python3.5/site-packages/setuptools/command/install_lib.py", line 16, in finalize_options

    self.set_undefined_options('install',('install_layout','install_layout'))

  File "/usr/local/lib/python3.5/distutils/cmd.py", line 290, in set_undefined_options

    setattr(self, dst_option, getattr(src_cmd_obj, src_option))

  File "/usr/local/lib/python3.5/distutils/cmd.py", line 103, in __getattr__

    raise AttributeError(attr)

AttributeError: install_layout

----------------------------------------
Cleaning up...
**_Command /home/andore/master-env/bin/python3.5 -c "import setuptools, tokenize;__file__='/tmp/pip-build-yonpcs2h/click/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-z_f40fma-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/andore/master-env/include/site/python3.5 failed with error code 1 in /tmp/pip-build-yonpcs2h/click
Storing debug log for failure in /home/andore/.pip/pip.log_**
(master-env)andore@AndOre-DevPi:~/AndOre/client $

**Comment by Hammersamatom** [comment]
[](http://stackoverflow.com/questions/18237484/raspberry-pi-psutil-install-error)
