### ISSUE TITLE
Flask Not Detected!

### ISSUE THREAD

**Issue by Hammersamatom** [baxter-cs/AndOre#202]
```
andore@AndOre-DevPi:~ $ sudo pip install flask --upgrade
[sudo] password for andore:
Downloading/unpacking flask from https://pypi.python.org/packages/63/2b/01f5ed23a78391f6e3e73075973da0ecb467c831376a0b09c0ec5afd7977/Flask-0.11.1-py2.py3-none-any.whl#md5=920be5772ee6399f70794d33a9eb9a13
  Downloading Flask-0.11.1-py2.py3-none-any.whl (80kB): 80kB downloaded
Requirement already up-to-date: itsdangerous>=0.21 in /usr/lib/python2.7/dist-packages (from flask)
Downloading/unpacking Werkzeug>=0.7 from https://pypi.python.org/packages/a9/5e/41f791a3f380ec50f2c4c3ef1399d9ffce6b4fe9a7f305222f014cf4fe83/Werkzeug-0.11.11-py2.py3-none-any.whl#md5=c63a21eedce9504d223ed89358c4bdc9 (from flask)
  Downloading Werkzeug-0.11.11-py2.py3-none-any.whl (306kB): 306kB downloaded
Downloading/unpacking Jinja2>=2.4 from https://pypi.python.org/packages/96/a1/c56bc4d99dc2663514a8481511e80eba8994133ae75eebdadfc91a5597d9/Jinja2-2.8-py2.py3-none-any.whl#md5=75acb6f1abfc46ed75f4fd392f321ac2 (from flask)
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB): 263kB downloaded
Requirement already up-to-date: click>=2.0 in /usr/local/lib/python2.7/dist-packages (from flask)
Requirement already up-to-date: MarkupSafe in /usr/lib/python2.7/dist-packages (from Jinja2>=2.4->flask)
Installing collected packages: flask, Werkzeug, Jinja2
  Found existing installation: Flask 0.10.1
    Not uninstalling Flask at /usr/lib/python2.7/dist-packages, owned by OS
  Found existing installation: Werkzeug 0.9.6
    Not uninstalling Werkzeug at /usr/lib/python2.7/dist-packages, owned by OS
  Found existing installation: Jinja2 2.7.3
    Not uninstalling Jinja2 at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed flask Werkzeug Jinja2
Cleaning up...
**andore@AndOre-DevPi:~ $ ./startServer.sh
Traceback (most recent call last):
  File "/home/andore/AndOre/client/client-server.py", line 1, in <module>
    from flask import Flask, render_template
ImportError: No module named 'flask'
Traceback (most recent call last):
  File "/home/andore/AndOre/ai_storage/ai_server.py", line 1, in <module>
    from flask import Flask, request, jsonify, url_for, render_template, make_response, redirect, current_app
ImportError: No module named 'flask'
Traceback (most recent call last):
  File "/home/andore/AndOre/server/server.py", line 1, in <module>
    from flask import Flask, request, jsonify, url_for, render_template, make_response, redirect, current_app
ImportError: No module named 'flask'
Traceback (most recent call last):
  File "/home/andore/AndOre/auth_service/auth_server.py", line 1, in <module>
    from flask import Flask, request, jsonify, url_for, render_template, make_response, redirect, current_app
ImportError: No module named 'flask'**
andore@AndOre-DevPi:~ $
```

**Comment by JCharante** [comment]
Not project specifict
